### ISSUE TITLE
Order in report

### ISSUE THREAD

**Issue by Chao0511** [sherbold/autorank#19]
In [Breadcrumbs[autorank](https://github.com/sherbold/autorank/tree/master)/[autorank](https://github.com/sherbold/autorank/tree/master/autorank)
/autorank.py ](https://github.com/sherbold/autorank/blob/master/autorank/autorank.py) Line 570:
Should "result.rankdf.index[0], result.rankdf.index[1]" be "result.rankdf.index[1], result.rankdf.index[0]" ? 

Thanks

**Comment by sherbold** [comment]
Thanks for reporting! This actually also (somewhat) affected the t-test. The problem was the output did not check the ordering of the means. This is now fixed and will be part of the next release. Let me know if you have further issues.
