### ISSUE TITLE
Add random_state from baycomp

### ISSUE THREAD

**Issue by Daniel300000** [sherbold/autorank#21]
I would like to suggest to adopt the "random_state" parameter from baycomp: https://github.com/janezd/baycomp/commit/4cffdb34ad812b0efa6177f3986d86bf48c6ccea. In this way, the results can be reproduced.

The only problem is that this would require replacing the PyPI version of baycomp with the version on GitHub. What do you think?

I am happy to create a pull request if needed.

**Comment by sherbold** [comment]
Thanks for the PR. I think that should be done. I will ask the baycomp devs first if they consider to publish a new release on Pypi, because I would prefer not to use the version directly from Github. 

Let's wait to see if this will happen, I will review the rest of the PR already.

**Comment by sherbold** [comment]
Problem solved, PR can go forward :)
