### ISSUE TITLE
Correct description

### ISSUE THREAD

**Issue by Daniel300000** [sherbold/autorank#23]
In accordance with [Kruschke and Liddell, 2018](https://doi.org/10.3758/s13423-016-1221-4), the ROPE is calculated correctly (d = 0.1 = ROPE / STD, therefore: ROPE = 0.1 * STD):

```
# half the size of a small effect size following Kruschke (2018)
if all_normal:
    cur_rope = rope*_pooled_std(reordered_data.iloc[:, i], reordered_data.iloc[:, j])
else:
    cur_rope = rope*_pooled_mad(reordered_data.iloc[:, i], reordered_data.iloc[:, j])
```

However, the description does not match:

> For normal data, the ROPE is defined as 0.1\*d, where d is the effect size (Cohen's d).
> For non-normal data, the ROPE is defined as 0.1\*gamma, where gamma is the effect size (Akinshin's gamma).

In the description, I guess it should be "0.1\*STD" and "0.1\*MAD"?

**Comment by sherbold** [comment]
You are right, this is somewhat badly worded in the description. I will fix this for the next release.

It will probably become something like this:
- For normal data, the ROPE is defined as 0.1*STD, where STD is the standard deviation. This means the ROPE is the area with an effect size of less than d=0.1, where d is Cohen's d. 
- For non-normal data, the ROPE is defined as 0.1*MAD, where MAD is the mean absolute deviation of the median. This means the ROPE is the area with an effect size of less than gamma=0.1, where gamma is Akinshin's gamma

That should fix the issue, right?.

**Comment by Daniel300000** [comment]
Yes, that looks good. Thank you very much.
