### ISSUE TITLE
Update to median_abs_deviation from scipy

### ISSUE THREAD

**Issue by d-diaz** [sherbold/autorank#5]
I've noticed that scipy docs indicate that `median_absolute_deviation` is now deprecated and recommend using `median_abs_deviation` instead. Doing a calculation of a sample array directly from numpy seems to indicate that the newer version implements the calculation correctly while the older version is different (for some reason I have not investigated).

**Comment by sherbold** [comment]
Thanks! I will take a look at this in the next days, but this looks like an easy merge.
