### ISSUE TITLE
Bug in dataframe ordering when using `create_report()`

### ISSUE THREAD

**Issue by delsner** [sherbold/autorank#7]
Great library thanks for creating it!
I have encountered a minor issue when printing the report about the statistical analysis.
From my analysis I receive the following output:

```python
# this is how I call autorank
result = autorank(df, alpha=0.05, order="descending", verbose=True) # (1)
create_report(result) # (2)

# output (1)
Fail to reject null hypothesis that data is normal for column $B_{c}$ (p=0.140985>=0.007143)
Fail to reject null hypothesis that data is normal for column $B_{h}$ (p=0.033133>=0.007143)
Fail to reject null hypothesis that data is normal for column $B_{l}$ (p=0.036612>=0.007143)
Rejecting null hypothesis that data is normal for column $B_{r}$ (p=0.000899<0.007143)  <- rejects for $B_{r}$
Fail to reject null hypothesis that data is normal for column $O$ (p=0.065865>=0.007143)
Fail to reject null hypothesis that data is normal for column $\hat{H}$ (p=0.937819>=0.007143)
Fail to reject null hypothesis that data is normal for column $\hat{M}$ (p=0.009967>=0.007143)
...
# output (2)
The statistical analysis was conducted for 7 populations with 22 paired samples.
The family-wise significance level of the tests is alpha=0.050.
We rejected the null hypothesis that the population is normal for the population $B_{c}$ (p=0.001). Therefore, we assume that not all populations are normal.
...
```

There seems to be some ordering problem here when `create_report()` is using `result.rankdf.index[i]` [here](https://github.com/sherbold/autorank/blob/master/autorank/autorank.py#L410).
The columns of the dataframe are not in the order they used to be when the results of the Shapiro-Wilk-Test were computed, leading to the wrong population (`$B_{c}$`) being printed (it should be `$B_{r}$`).
I could not yet figure out, where exactly this re-ordering occurs that breaks the report function.

It would be great, if you could have a look at it.
Cheers!

**Comment by sherbold** [comment]
Thanks for the report. This looks quite annoying, I will check where this happens in the next days.

**Comment by sherbold** [comment]
I pushed a fix to the latest master. Could you check if it solves the problem? The solution was a bit ugly, because the sorting happens a couple of functions calls away from where the p-values of the normality check are stored. 

If this is fixed (and a currently pending PR is through), I would then release 1.1.2 with the fix.

**Comment by delsner** [comment]
Thanks, I will check it in the next days.

**Comment by delsner** [comment]
Works for me!
