### ISSUE TITLE
Is it possible to let the user choose which test to run?

### ISSUE THREAD

**Issue by SophiaJia** [sherbold/autorank#8]
Thanks for this awesome tool, but I am wondering if it is possible to let the user decide if they want a parametric test or a nonparametric test?  That will allow some flexibility to this function. For example, I want to get a CD plot for my test, but it always returns a CI plot.

**Comment by sherbold** [comment]
Thanks for your interest in autorank!
I will consider how such a "force" option could be implemented, without breaking the inherent design principle of autorank, i.e., to hinder using the "wrong" statistical methods. 
Maybe an optional parameter, combined with a warning, would be an option. However, I am not yet sure when I will have time to work on this.

**Comment by sherbold** [comment]
@SophiaJia I just pushed a new version of autorank to the master with a new parameter: `force_mode`.

Without using the parameter, nothing should change. If you set the parameter to `'parametric'` you should always get the t-test/ANOVA and mean and standard deviation. If you set the parameter to `'nonparametric'` you should always get the Wilcoxon test/Friedman-Nemenyi test and the median and MAD. 

In case the choise of tests is suboptimal, the report mentions this. 

Does this solve your issue?

**Comment by sherbold** [comment]
I assume this is resolved and close now.
