### ISSUE TITLE
bayesian explain 

### ISSUE THREAD

**Issue by nasergh** [sherbold/autorank#9]
Hello,
thanks for your nice tools,
for using the bayesian result i have a problem because in your paper and original paper did not describe like you provided.
please add more detail or provide a video and explain one bayesian example, to user can understand what is the CI, y, P values, Magnitude and decision.
because normally people that use your tools don't know statistics and putting these words without explaining them is useless, at least for me!
i saw it's provided the report but it's not enough to understand the table.
Thanks

**Comment by sherbold** [comment]
I might add links to tutorials in the future, but the goal here to simplify using stats, especially the choice of appropriate methods and the correct reporting of results - not teaching these methods.
